### ISSUE TITLE
Error output following creation - most options set to 'No'.

### ISSUE THREAD

**Issue by mannp** [eunjae-lee/create-gatsby-theme#3]
Hi there

Thanks for creating this :)

Got the following error with all questions answered 'No', except the final one to add sample code....

Edit: I should add the error didn't appear to stop things from working...

● The release script has been added.
  Import this repository at https://circleci.com
  To prepare a release, you can run the following command:
    yarn release:prepare
  To finish the setup on CircleCI side, check out the following:
  https://github.com/algolia/shipjs/blob/master/GUIDE.md#automate-part-3-shipjs-trig.......

● `netlify.toml` has been added.
  Import this repository at https://www.netlify.com

TypeError: Cannot destructure property `hubExists` of 'undefined' or 'null'.
    at Object.finished (/Users/local/.npm/_npx/4253/lib/node_modules/create-gatsby-theme/src/plugins/createGitHubRepo.js:35:24)
    at runPlugins (/Users/local/.npm/_npx/4253/lib/node_modules/create-gatsby-theme/src/runPlugins.js:33:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Proxy.cli (/Users/local/.npm/_npx/4253/lib/node_modules/create-gatsby-theme/src/cli.js:37:3)
    at async /Users/local/.npm/_npx/4253/lib/node_modules/create-gatsby-theme/bin/cli.js:6:5

**Comment by eunjae-lee** [comment]
@mannp
Hello, thanks for writing this issue!
I will take a look at this.

**Comment by eunjae-lee** [comment]
@mannp Released at v0.0.2 👍

**Comment by mannp** [comment]
@eunjae-lee Cool, thanks for the quick fix :)
